version: '3'

services:
  yezzey:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: yezzey
    hostname: yezzey

  s3:
    image: minio/minio:RELEASE.2021-06-07T21-40-51Z
    container_name: yezzey_s3
    hostname: s3
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    entrypoint: sh
    command: >
      -c 'mkdir -p /export/yezzey_test_bucket
      &&  /usr/bin/minio server /export'