version: '3'

services:
  yezzey:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: yezzey
    hostname: yezzey
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    entrypoint: ["./make_cluster.sh"]
    depends_on:
      createbuckets:
        condition: service_completed_successfully

  s3:
    image: minio/minio
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "AKIAIOSFODNN7EXAMPLE"
      MINIO_ROOT_PASSWORD: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    volumes:
      - ./yezzey_test/.minio:/root/.minio
  
  createbuckets:
    image: minio/mc
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set --insecure myminio https://s3:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc mb --insecure myminio/yezzey-test-bucket;
      # /usr/bin/mc policy set --insecure public myminio/yezzey-test-bucket;
      exit 0;
      "

  # s3:
  #   build: 
  #     dockerfile: ./Dockerfile.s3
  #     context: .
  #   container_name: yezzey_s3
  #   hostname: s3
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #     - "443:443"
  #   environment:
  #     - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
  #     - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  #   entrypoint: sh
  #   command: >
  #     -c 'mkdir -p /export/yezzey_test_bucket
  #     &&  ./minio  \
  #         --certs-dir /ets/yezzey-ssl \
  #           server \
  #           --console-address ":9001" \
  #             /export'
