version: '3'

services:
  yezzey:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: yezzey
    hostname: yezzey
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    entrypoint: ["./make_cluster.sh"]
    depends_on:
      - s3

  s3:
    build: 
      dockerfile: ./Dockerfile.s3
      context: .
    container_name: yezzey_s3
    hostname: s3
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    entrypoint: sh
    volumes:
      - ~/certs:/certs
    command: >
      -c 'mkdir -p /export/yezzey_test_bucket
      &&  /usr/bin/minio --certs-dir /certs server /export'
